== Account

An `Account` reflects to a customers cost center. A project may know about several cost centers - `Accounts`. The `Account` information is
usually defined at project setup and does not change at runtime. So it is not foreseen that `Account` instances are created or deleted
through the API.

=== Account Index
The index with all possible operations can be retrieved with an `GET request:

include::{generated}/àcc-index/http-request.adoc[]

The response lists all the operations with a name and the corresponding href link:

include::{generated}/acc-index/http-response.adoc[]

=== Find all Accounts
To retrieve a list of all existing `Accounts` a client must send a `GET` request to the server:

include::{generated}/acc-find-all/http-request.adoc[]

The response contains all existing `Accounts`:

include::{generated}/tut-find-all/http-response.adoc[]

=== Find an Account
The `name` and the `identifier` of the `Account` are unique and mandatory attributes. So an `Account` can be searched for both fields.

Find an `Account` by name:
include::{generated}/acc-find-byName/http-request.adoc[]

or find an `Account` by identifier:
include::{generated}/acc-find-byIdentifier/http-request.adoc[]

The server responds with the Account entity if it exists:
include::{generated}/tut-find-byName/http-response.adoc[]

or with a `404-Not Found` if no `Account` exists:
include::{generated}/tut-find-byName404/http-response.adoc[]
