= RESTful API
({bversion}-{bnumber})
Heiko Scherrer;
:doctype: book
:icons: font
:toc:
:sectanchors:
:sectlinks:
:toclevels: 4
:source-highlighter: highlightjs
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= Overview
This guide describes the RESTful API of the OpenWMS.org COMMON Base Service module and its usage. Some general terms and definitions
are explained and declared in the first part of the document whereas in the second part the usage of the API is shown in
a more use-case-driven approach.

[[resources-prg]]
= Resources


image::ClassDiagram.svg[]

== Location
A `Location` represents a physical or virtual place in a warehouse. Could be something like a storage location in the stock or a location on
the conveyor. Even error locations can be represented with the `Location`. Multiple `Locations` with same characteristics are grouped to a
`LocationGroup`.

The API allows to search for `Locations` and to mutate the `Locations` state.

=== Find Location by Coordinate

=== Find Location by PLC code
Send a HTTP GET request with the PLC code as query parameter to find a `Location` identified by this PLC code.

include::{generated}/loc-find-plc/http-request.adoc[]

If the `Location` exists the server responds with

include::{generated}/loc-find-plc/http-response.adoc[]

If no `Location` with the requested PLC code exists, the server responds with

include::{generated}/loc-find-plc-404/http-response.adoc[]

=== Find Locations of a LocationGroup

=== Change the state of a Location

== Target
A `Target` is a `Location` or a group of `Locations` (`LocationGroup`) where a `TransportUnit` may be sent to.

A `Target` can be locked for *inbound*/*outbound*, for *operation* or for both. When the `Target` is locked for inbound, no new
`TransportUnit` movements (`TransportOrders` in automatic warehouses) are created to this `Target` (like a Putaway lock).
In contrast, no movements can be created away from this `Target` if it is locked for outbound (like Allocation). Locking inbound/outbound
has no impact on the operation mode of the `Target`. So the `Target` may _still process_ existing orders, even if it is locked for
inbound/outbound.

The operation mode of a `Target` is controlled separately. If the `Targets` operation mode is set to `*BLOCKED*` the `Target` stops
all operations and does no longer process any commands or telegrams.

=== Locking Inbound/Outbound
Locking the Inbound/Outbound of a `Target` is controlled with a HTTP POST request against the URI `/v1/targets/{name}` with a set of
query parameters.

|===
| HTTP Verb | Query Param `type` | Query Param `mode` | Description
| `POST`
| `ALLOCATION_LOCK`
| `IN`
| Lock the `Target` for Inbound allocation


| `POST`
| `ALLOCATION_LOCK`
| `OUT`
| Lock the `Target` for Outbound allocation


| `POST`
| `ALLOCATION_LOCK`
| `IN_AND_OUT`
| Lock the `Target` for Inbound and Outbound allocation


| `POST`
| `ALLOCATION_LOCK`
| `NONE`
| Release the `Target` for all kind of allocation
|===

==== Lock Inbound (Putaway, Infeed)
To lock a `Target` to be not considered in inbound, like Putaway, the server requires a HTTP POST request with the lock type
`type=ALLOCATION_LOCK` and the `*mode=IN*`.

include::{generated}/all-lock-in-lg-IPOINT/http-request.adoc[]

==== Lock Outbound (Dispatching, Allocation, Outfeed)
To lock a `Target` for outbound, like Allocation and Outfeed, the server requires a HTTP POST request with the lock type
`type=ALLOCATION_LOCK` and the `*mode=OUT*`.

include::{generated}/all-lock-out-lg-IPOINT/http-request.adoc[]

==== Lock Inbound & Outbound
To lock a `Target` for inbound and outbound, like Putaway and Allocation, the server requires a HTTP POST request with the
lock type `type=ALLOCATION_LOCK` and the `*mode=IN_AND_OUT*`.

include::{generated}/all-lock-inout-lg-IPOINT/http-request.adoc[]

==== Release Lock
To release all locks on a `Target` and allow any inbound and outbound operation, the server requires a HTTP POST request with the lock
type `type=ALLOCATION_LOCK` and the `*mode=NONE*`.

include::{generated}/all-lock-none-lg-IPOINT/http-request.adoc[]

==== Response: Success
In any of the previous cases the server responds with the following success message.

include::{generated}/all-lock-none-lg-IPOINT/http-response.adoc[]

=== Locking Operational Processing
A `Target` could also be locked for operation only but not for further Allocation. This means, the `Target` is active and looks available
in warehouse counting and order allocation but is currently out-of-order and not ready to execute any (physical) operation. This is useful
for planned short term locks, where a `Target` is taken out of operation but should still be considered by the system.

Like the infeed/outfeed locking an *operational lock* can be set to different modes.

|===
| HTTP Verb | Query Param `type` | Query Param `mode` | Description
| `POST`
| `OPERATION_LOCK`
| `IN`
| Lock the `Target` for all inbound operations


| `POST`
| `OPERATION_LOCK`
| `OUT`
| Lock the `Target` for all outbound operations


| `POST`
| `OPERATION_LOCK`
| `IN_AND_OUT`
| Lock the `Target` for all inbound and outbound operations


| `POST`
| `OPERATION_LOCK`
| `NONE`
| Release the `Target` for all kind of operations
|===

==== Lock for inbound Operations
To lock a `Target` for inbound operations only, the server requires a HTTP POST request with the lock type
`type=OPERATION_LOCK` and the `*mode=IN*`.

include::{generated}/all-olock-in-lg-IPOINT/http-request.adoc[]

==== Lock for outbound Operations
To lock a `Target` for outbound operations only, the server requires a HTTP POST request with the lock type
`type=OPERATION_LOCK` and the `*mode=OUT*`.

include::{generated}/all-olock-out-lg-IPOINT/http-request.adoc[]

==== Lock inbound & outbound Operations
To lock a `Target` for inbound and outbound operations, the server requires a HTTP POST request with the
lock type `type=OPERATION_LOCK` and the `*mode=IN_AND_OUT*`.

include::{generated}/all-olock-inout-lg-IPOINT/http-request.adoc[]

==== Release Lock
To release all operational locks on a `Target` and allow any inbound and outbound operation, the server requires a HTTP POST request with
the lock type `type=OPERATION_LOCK` and the `*mode=NONE*`.

include::{generated}/all-olock-none-lg-IPOINT/http-request.adoc[]

==== Response: Success
In any of the previous cases the server responds with the following success message.

include::{generated}/all-olock-none-lg-IPOINT/http-response.adoc[]

=== Locking / Unlocking a Target for Allocation and Processing
If a `Target` locked for operation it does not process and requests anymore. In case of a physical `Target`, like a Crane, no new movements
are accepted and the Crane will stop working. This depends on the implemented Crane strategy. The Crane could stop immediately or after it
finishes the current operation.

To permanently lock or unlock a `Target` for allocation _and_ processing send a HTTP POST request with the name of the `Target` to the
server. Locking  the `Target` allows an optional flag to signal a re-allocation of already assigned movements and orders.

In this example the `Target` is a `LocationGroup` with the name `IPOINT` that gets locked. The server is requested to re-allocate existing
orders.

include::{generated}/lock-lg-IPOINT/http-request.adoc[]

To unlock the same `Target` with name `IPOINT`:

include::{generated}/unlock-lg-IPOINT/http-request.adoc[]

==== Response: Success
If the server has successfully locked or unlocked the `Target` the response is:

include::{generated}/lock-lg-IPOINT/http-response.adoc[]

==== Response: Target does not exist
If the given `Target` (FOO) does not exist the server responds with:

include::{generated}/lock-lg-unknown/http-response.adoc[]





