= OpenWMS.org COMMON: RESTful API (Common Service)
({bversion}-{bnumber})
Heiko Scherrer; Markus Schneider;
:doctype: book
:icons: font
:toc:
:sectanchors:
:sectlinks:
:toclevels: 4
:source-highlighter: highlightjs
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

Copyright © 2005-2020

Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies
and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.

[[overview]]
= Overview
This guide describes the RESTful API of the OpenWMS.org COMMON Base Service module and its usage. Some general terms and definitions
are explained and declared in the first part of the document whereas in the second part the usage of the API is shown in
a more use-case-driven approach.

= Representation Formats
Basically JSON is used as representation format by default if not otherwise requested or mentioned below. XML format is supported for the
index pages as well, but must be requested. Furthermore a vendor specific JSON format is used to represent resource representations.
Therefore it is absolutely required that the `Accept` header denotes the demanded type. Find the type in the examples below.

== Dates in JSON
Date or datetime fields are not treated specially in JSON. Within the scope of this API a date or datetime field is always expected and
rendered as JSON String in ISO8601 format with timezone information (GMT) and milliseconds: `yyyy-MM-dd'T'HH:mm:ss.SSSZ`.

== Embedded Entities
For the sake of convenience some response entities may included embedded entities or even parts of it. A reference to the actual entity is
provided as HAL link as well.

== Error Responses
Beside the actual representation of resources, the server may result an error response in JSON format that contains basic information about
the error occurred. This information is additional to the standard HTTP status code and may help clients to identify the error cause in
order to re-phrase and send the request again.

Currently there are two types of errors with their own response formats.

=== Server Declined Errors
This kind of errors are sent by the server runtime environment even before the request had a chance to be processed.

An example response looks like this:

```
{
    "timestamp": 1512400854941,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "org.ameba.oauth2.InvalidTokenException",
    "message": "JWT expired at 2017-12-04T15:04:43Z. Current time: 2017-12-04T15:20:54Z, ...",
    "path": "/v1/transport-units?bk=00000000000000004711"
}
```

The JSON structure contains the following fields.

|===
| Property Name | Description

| timestamp     | When the error occurred on server side
| status        | The http status of the error
| error         | A short error text
| exception     | Internal class name of the Java exception type
| message       | A more descriptive error text describing the error in detail
| path          | The part of the URI for the REST resource that was queried
|===

=== API Declined Errors
Those errors are thrown within the REST API validation and processing logic. For example, if a client request does not match the expected
format or has produced an error on server side, the API will decline the request and return a response with status client-side error (4xx).

The structure of the response is aligned to the RFC7808. An example response looks like this:

```
{
    "message": "LocationGroup with name [NOT_EXISTS] not found",
    "messageKey": "COMMON.LOCATION_GROUP_NOT_FOUND",
    "obj" : [ "NOT_EXISTS" ],
    "httpStatus" : "404",
    "class" : "String"
}
```

The JSON structure contains the following fields.

|===
| Property Name | Description

| message       | A short error text
| messageKey    | An unique identifier across the API that can be used to identify and translate the error message on the client side
| obj           | An array of possible passed arguments to the message
| httpStatus    | The http status of the error
| class         | The arguments type
|===

Following message keys are currently used:


|===
| Message Key | Description | Action

| not.found                            | The requested resource has not been found      | The resource does not exist anymore or has never existed. The resource identifier must be verified
| COMMON.BARCODE_NOT_FOUND             | The TransportUnit does not exist               | Verify the identifying attribute passed to the API
| COMMON.LOCATION_NOT_FOUND            | The requested Location does not exist          | Verify the identifying attribute passed to the API
| COMMON.LOCATION_GROUP_NOT_FOUND      | The requested LocationGroup does not exist     | Verify the identifying attribute passed to the API
| COMMON.TRANSPORT_UNIT_TYPE_NOT_FOUND | The requested TransportUnitType does not exist | Verify the identifying attribute passed to the API
|===


[[sitemap-prg]]
= Interaction Map

This chapter describes the actions, respectively the flow of actions, an API consumer can perform to achieve the use cases. The COMMON
Service API deals essentially with `Locations`, `LocationGroups` and `TransportUnits` therefore those entities are centric elements in the
interaction model and can be referenced from the main index page.

Like human readable websites provide a sitemap, a machine readable API can be visualized with an interaction map. A fully automated RESTful
maturity-level-3 API offers index resources beside typical business resources. The API entry point is the top-level index resource that is
used to navigate to all possible entities with their operations.

image::common-service-index.svg[]

This top-level, or root, index page offers further links to primary resources, like `Locations`, `LocationGroups` and `TransportUnits`.

[[resources-prg]]
= Resources

A description of all used API resources.

image::ClassDiagram.svg[]

== Index

The initial HTTP request to retrieve information about all available resources looks like the following. The Index page is a public
available resource and does not need any authentication.

include::{generated}/get-index/http-request.adoc[]

The Index resource is returned in the response body with the response status of 200-OK. This main Index lists all primary resource entities
to follow next.

include::{generated}/get-index/http-response.adoc[]

A client application must only know about the agreed link names and follow the corresponding `href` link to navigate further.

== Location

A `Location` represents a physical or virtual place in a warehouse. Could be something like a storage location in the stock or a location on
the conveyor. Even error locations can be represented with the `Location`. Multiple `Locations` with same characteristics are grouped to a
`LocationGroup`.

A `Location` is identified by the 5-tuple coordinate, the LocationID, as well as a persistent key (the pKey). The PLC Code is an additional
identifier of a `Location` that might be null in project setups. It is the identifying name a PLC unit uses in automatic warehouses - not
used in manual warehouses.

A `Location` always belongs to a `LocationGroup` where the name of that group is stored in the `locationGroupName` property.

A `Location` can be a `Target` to send `TransportUnits` to, i.e. the target of an automatic `TransportOrder` or a manual `Movement`.

Multiple state properties with different meaning exist for a `Location`. The `plcState` is exclusively managed by the PLC in automatic
warehouses. Any error signaled by the PLC are stored on this field with a value greater than 0. Two other state fields `incomingActive` and
`outgoindActive` are used to control the material flow control of this `Location`. If `incomingActive` is set to `false`, the particular
`Location` is not considered in Inbound activities, like Putaway. Whereas the `outgoindActive` can be set to `false` to lock Outbound
operations off this `Location`.

The API allows to search for `Locations` and to mutate the `Locations` state.

=== Location Index
The Location Index with all possible operations can be retrieved with the following GET request:

include::{generated}/loc-index/http-request.adoc[]

The response lists all the operations with a name and the corresponding href link:

include::{generated}/loc-index/http-response.adoc[]

=== Find Location by Coordinate
Send a HTTP GET request with the 5-tuple coordinate as query parameter to find a `Location` identified by this coordinate.

include::{generated}/loc-find-coordinate/http-request.adoc[]

If the `Location` exists the server responds with

include::{generated}/loc-find-coordinate/http-response.adoc[]

If the `Location` with the requested coordinate does not exist, the server responds with

include::{generated}/loc-find-coordinate-404/http-response.adoc[]

If the passed coordinate is not well formatted and rejected by the server the response looks like

include::{generated}/loc-find-coordinate-400/http-response.adoc[]

=== Find Location by Coordinate with Wildcards
The API to search for `Locations` also accepts typical SQL wildcards in each part of the 5-tuple coordinate. Let's assume one searches for
all Lift `Locations` in the Flat Good area, this could look like this:

include::{generated}/loc-find-coordinate-wildcard/http-request.adoc[]

In this case the Flat Good area has only 2 Lift positions and the server returns both:

include::{generated}/loc-find-coordinate-wildcard/http-response.adoc[]

If the search query did not find any `Locations` the server responds with:

include::{generated}/loc-find-coordinate-wildcard-404/http-response.adoc[]

=== Find Location by PLC code
Send a HTTP GET request with the PLC code as query parameter to find a `Location` identified by this PLC code.

include::{generated}/loc-find-plc/http-request.adoc[]

If the `Location` exists the server responds with

include::{generated}/loc-find-plc/http-response.adoc[]

If no `Location` with the requested PLC code exists, the server responds with

include::{generated}/loc-find-plc-404/http-response.adoc[]

=== Find Locations of a LocationGroup
Send a HTTP GET request with the name of a `LocationGroup` as query parameter to find all `Locations` that belong to this group.

include::{generated}/loc-find-in-lg/http-request.adoc[]

The server responds with the list of all `Locations` - the name of the `LocationGroup` is not validated.

include::{generated}/loc-find-in-lg/http-response.adoc[]

The server accepts multiple `LocationGroup` names as request parameter to get a combined list of `Locations` that belong to group with name
`ZILE` and `FGRECEIVING`:

include::{generated}/loc-find-in-lg-multiple/http-request.adoc[]

Wildcards in the `LocationGroup` name are supported if only one `LocationGroup` name is provided:

include::{generated}/loc-find-in-lg-wc/http-request.adoc[]

The response is a list of `Locations` that belong to a `LocationGroup` where the name starts with `IP` (matching the groups `IPOINT`,
`IPOINT1` and `IPOINT2` in this example:

include::{generated}/loc-find-in-lg-wc/http-response.adoc[]

=== Change a Location's State
Send a HTTP PATCH request with the persistent identifying key of an existing `Location` along the new state decoded as `ErrorCodeVO` request
parameter.

include::{generated}/loc-state-404/http-request.adoc[]

If the `Location` with the given persistent key does not exist, the server responds with

include::{generated}/loc-state-404/http-response.adoc[]

The `ErrorCodeVO` contains a ternary error bitmap that decodes all state information. It is expected as 8-digit String with allowed symbols
`*|0|1`. Each digit is assigned to one of the state attribute of the `Location` or `LocationGroup`:

|===
| Digit Position (RtL) | Assigned attribute

| 2^0^                 | Location.incomingActive
| 2^1^                 | Location.outgoingActive
| 2^2^                 | Location.groupStateIn
| 2^3^                 | Location.groupStateOut
|===

The following table shows all currently accepted decodings of the `ErrorCodeVO.errorCode` String that is sent with the request body:
|===
| ErrorCode String                                                                   | Description

| `{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}` | Content is ignored
| `{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}00`                   | Release Location for Inbound and Outbound operations
| `{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}01`                   | Lock Inbound operation to the Location
| `{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}10`                   | Lock Outbound operation from the Location
| `{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}11`                   | Lock Inbound and Outbound operation for the Location
|===

In this example a `Location` identified with the given persistent key is locked for Inbound operations with the following request:

include::{generated}/loc-state-in/http-request.adoc[]

If the server could lock the `Location` successfully the response looks like:

include::{generated}/loc-state-in/http-response.adoc[]

Beside locking the `Location` for Inbound- and Outbound processing it is also possible to change the PLC state of the `Location` through
this API. Therefor the `ErrorCodeVO` data structure contains a property `plcState` that can be set to a numeric integer value. Usually a
PLC state of `0` means the `Location` is not blocked and available for any operation. A PLC may set the state to a value greater than 0 to
signal an error occurred on the `Location`.

Set the `plcState` to `31` (In terms of https://interface21-io.gitbook.io/osip[OSIP] this means `Location unexpected occupied`):

include::{generated}/loc-plcstate/http-request.adoc[]

If the server could set the state successfully the response is:

include::{generated}/loc-plcstate/http-response.adoc[]

== LocationGroup

A `LocationGroup` is used to group `Locations` with same characteristics or to define a warehouse area that can be seen as one cohesive
block controlled by one single subsystem.

=== LocationGroup Index
The index with all possible operations can be retrieved with the following GET request:

include::{generated}/lg-index/http-request.adoc[]

The response lists all the operations with a name and the corresponding href link:

include::{generated}/lg-index/http-response.adoc[]

=== Find all LocationGroups
To retrieve a list of all existing `LocationGroups` a client must send a GET request to the server:

include::{generated}/lg-find-all/http-request.adoc[]

If no `LocationGroups` exist the returned array is empty otherwise the response looks like:

include::{generated}/lg-find-all/http-response.adoc[]

Each `LocationGroup` has a link to its parent `LocationGroup` except the root `LocationGroup` that has no parent. Notice the returned
`Content-Type` is `application/hal+json` that enables support for hypermedia links.

=== Find LocationGroup by Name
Send a HTTP GET request with the unique name of the `LocationGroup`.

include::{generated}/lg/shall_findby_name/http-request.adoc[]

Request parameters:

include::{generated}/lg/shall_findby_name/request-parameters.adoc[]

If the `LocationGroup` exists the server responds with

include::{generated}/lg/shall_findby_name/http-response.adoc[]

If the `LocationGroup` with the given name does not exist, the server responds with

include::{generated}/lg-find-name-404/http-response.adoc[]

=== Find multiple LocationGroups by Name
Send a HTTP GET request with a list of unique `LocationGroup` names.

include::{generated}/lg/shall_findby_names/http-request.adoc[]

Request parameters:

include::{generated}/lg/shall_findby_names/request-parameters.adoc[]

The server sends back a list of all `LocationGroups` or an empty list if no `LocationGroups` exist.

include::{generated}/lg/shall_findby_names/http-response.adoc[]

=== Change a LocationGroup's State
A `LocationGroup` has an inbound and an outbound state, sometimes also refered as infeed or outfeed state. Both states can be set to
`AVAILABLE` or `NOT_AVAILABLE` independent from each other. Is a `LocationGroup` not available for infeed, then no transports towards this
`LocationGroup` are created, similar is true for the outbound state.

To change the state of a `LocationGroup` a `PATCH` request on the identified resource is accepted:

include::{generated}/lg/shall_change_state_p-key/http-request.adoc[]

Request path variables:

include::{generated}/lg/shall_change_state_p-key/path-parameters.adoc[]

Request parameters:

include::{generated}/lg/shall_change_state_p-key/request-parameters.adoc[]

If the state change operation could be processed successfully, the server responds with:

include::{generated}/lg/shall_change_state_p-key/http-response.adoc[]

If the resource can't be identified the server response looks like:

include::{generated}/lg-state-404/http-response.adoc[]

Instead of passing both state values for inbound and outbound directly as query parameters it is also possible to encode the state into a
8-digit bitmap field and pass it to the request. This is very handy when the subsystem (aka. PLC) sends an error bitmap to the server that
can then directly passed to the API.

include::{generated}/lg/shall_change_state/http-request.adoc[]

Request parameters:

include::{generated}/lg/shall_change_state/request-parameters.adoc[]

The server response is:

include::{generated}/lg/shall_change_state/http-response.adoc[]

== Target
A `Target` is a `Location` or a group of `Locations` (`LocationGroup`) where a `TransportUnit` may be sent to.

A `Target` can be locked for *inbound*/*outbound*, for *operation* or for both. When the `Target` is locked for inbound, no new
`TransportUnit` movements (`TransportOrders` in automatic warehouses) are created to this `Target` (like a Putaway lock).
In contrast, no movements can be created away from this `Target` if it is locked for outbound (like Allocation). Locking inbound/outbound
has no impact on the operation mode of the `Target`. So the `Target` may _still process_ existing orders, even if it is locked for
inbound/outbound.

The operation mode of a `Target` is controlled separately. If the `Targets` operation mode is set to `*BLOCKED*` the `Target` stops
all operations and does no longer process any commands or telegrams.

=== Locking Inbound/Outbound
Locking the Inbound/Outbound of a `Target` is controlled with a HTTP POST request against the URI `/v1/targets/{name}` with a set of
query parameters.

|===
| HTTP Verb | Query Param `type` | Query Param `mode` | Description

| `POST`
| `ALLOCATION_LOCK`
| `IN`
| Lock the `Target` for Inbound allocation
| `POST`
| `ALLOCATION_LOCK`
| `OUT`
| Lock the `Target` for Outbound allocation
| `POST`
| `ALLOCATION_LOCK`
| `IN_AND_OUT`
| Lock the `Target` for Inbound and Outbound allocation
| `POST`
| `ALLOCATION_LOCK`
| `NONE`
| Release the `Target` for all kind of allocation
|===

==== Lock Inbound (Putaway, Infeed)
To lock a `Target` to be not considered in inbound, like Putaway, the server requires a HTTP POST request with the lock type
`type=ALLOCATION_LOCK` and the `*mode=IN*`.

include::{generated}/all-lock-in-lg-IPOINT/http-request.adoc[]

==== Lock Outbound (Dispatching, Allocation, Outfeed)
To lock a `Target` for outbound, like Allocation and Outfeed, the server requires a HTTP POST request with the lock type
`type=ALLOCATION_LOCK` and the `*mode=OUT*`.

include::{generated}/all-lock-out-lg-IPOINT/http-request.adoc[]

==== Lock Inbound & Outbound
To lock a `Target` for inbound and outbound, like Putaway and Allocation, the server requires a HTTP POST request with the
lock type `type=ALLOCATION_LOCK` and the `*mode=IN_AND_OUT*`.

include::{generated}/all-lock-inout-lg-IPOINT/http-request.adoc[]

==== Release Lock
To release all locks on a `Target` and allow any inbound and outbound operation, the server requires a HTTP POST request with the lock
type `type=ALLOCATION_LOCK` and the `*mode=NONE*`.

include::{generated}/all-lock-none-lg-IPOINT/http-request.adoc[]

==== Response: Success
In any of the previous cases the server responds with the following success message.

include::{generated}/all-lock-none-lg-IPOINT/http-response.adoc[]

=== Locking Operational Processing
A `Target` could also be locked for operation only but not for further Allocation. This means, the `Target` is active and looks available
in warehouse counting and order allocation but is currently out-of-order and not ready to execute any (physical) operation. This is useful
for planned short term locks, where a `Target` is taken out of operation but should still be considered by the system.

Like the infeed/outfeed locking an *operational lock* can be set to different modes.

|===
| HTTP Verb | Query Param `type` | Query Param `mode` | Description

| `POST`
| `OPERATION_LOCK`
| `IN`
| Lock the `Target` for all inbound operations
| `POST`
| `OPERATION_LOCK`
| `OUT`
| Lock the `Target` for all outbound operations
| `POST`
| `OPERATION_LOCK`
| `IN_AND_OUT`
| Lock the `Target` for all inbound and outbound operations
| `POST`
| `OPERATION_LOCK`
| `NONE`
| Release the `Target` for all kind of operations
|===

==== Lock for inbound Operations
To lock a `Target` for inbound operations only, the server requires a HTTP POST request with the lock type
`type=OPERATION_LOCK` and the `*mode=IN*`.

include::{generated}/all-olock-in-lg-IPOINT/http-request.adoc[]

==== Lock for outbound Operations
To lock a `Target` for outbound operations only, the server requires a HTTP POST request with the lock type
`type=OPERATION_LOCK` and the `*mode=OUT*`.

include::{generated}/all-olock-out-lg-IPOINT/http-request.adoc[]

==== Lock inbound & outbound Operations
To lock a `Target` for inbound and outbound operations, the server requires a HTTP POST request with the
lock type `type=OPERATION_LOCK` and the `*mode=IN_AND_OUT*`.

include::{generated}/all-olock-inout-lg-IPOINT/http-request.adoc[]

==== Release Lock
To release all operational locks on a `Target` and allow any inbound and outbound operation, the server requires a HTTP POST request with
the lock type `type=OPERATION_LOCK` and the `*mode=NONE*`.

include::{generated}/all-olock-none-lg-IPOINT/http-request.adoc[]

==== Response: Success
In any of the previous cases the server responds with the following success message.

include::{generated}/all-olock-none-lg-IPOINT/http-response.adoc[]

=== Locking / Unlocking a Target for Allocation and Processing
If a `Target` locked for operation it does not process and requests anymore. In case of a physical `Target`, like a Crane, no new movements
are accepted and the Crane will stop working. This depends on the implemented Crane strategy. The Crane could stop immediately or after it
finishes the current operation.

To permanently lock or unlock a `Target` for allocation _and_ processing send a HTTP POST request with the name of the `Target` to the
server. Locking  the `Target` allows an optional flag to signal a re-allocation of already assigned movements and orders.

In this example the `Target` is a `LocationGroup` with the name `IPOINT` that gets locked. The server is requested to re-allocate existing
orders.

include::{generated}/lock-lg-IPOINT/http-request.adoc[]

To unlock the same `Target` with name `IPOINT`:

include::{generated}/unlock-lg-IPOINT/http-request.adoc[]

==== Response: Success
If the server has successfully locked or unlocked the `Target` the response is:

include::{generated}/lock-lg-IPOINT/http-response.adoc[]

==== Response: Target does not exist
If the given `Target` (FOO) does not exist the server responds with:

include::{generated}/lock-lg-unknown/http-response.adoc[]

== TransportUnitType

A `TransportUnitType` is a type of a certain `TransportUnit`. Typically to store some static attributes of `TransportUnits`, such as the
length, the height, or the weight of `TransportUnits`. It is possible to group and characterize `TransportUnits`.

=== TransportUnitType Index
The index with all possible operations can be retrieved with the following GET request:

include::{generated}/tut-index/http-request.adoc[]

The response lists all the operations with a name and the corresponding href link:

include::{generated}/tut-index/http-response.adoc[]

=== Find all TransportUnitTypes
To retrieve a list of all existing `TransportUnitTypes` a client must send a GET request to the server:

include::{generated}/tut-find-all/http-request.adoc[]

The response contains all existing `TransportUnitTypes`:

include::{generated}/tut-find-all/http-response.adoc[]

=== Find a TransportUnitType by Name
Each `TransportUnitType` has an unique name by that it can be identified. Query the resource with a `type` parameter:

include::{generated}/tut-find-type/http-request.adoc[]

If the `TransportUnitType` exists the response looks like:

include::{generated}/tut-find-type/http-response.adoc[]

If no `TransportUnitType` with the given name exist the server sends a 404-NOT FOUND:

include::{generated}/tut-find-type-404/http-response.adoc[]

== TransportUnit
A TransportUnit is an item like a box, a toad, a bin or a pallet that is moved within a warehouse and can carry goods. Used as container to
transport items like `LoadUnits`. It is moved between `Locations`.

=== TransportUnit Index
The index with all possible operations can be retrieved with the following GET request:

include::{generated}/tu-index/http-request.adoc[]

The response lists all the operations with a name and the corresponding href link:

include::{generated}/tu-index/http-response.adoc[]

=== Find by Barcode
Find a `TransportUnit` by its unique `Barcode`.

include::{generated}/tu-find-by-barcode/http-request.adoc[]

If the `TransportUnit` has been found the server returns a JSON representation:

include::{generated}/tu-find-by-barcode/http-response.adoc[]

In case a `TransportUnit` with the requested `Barcode` == `9999` does not exist the response looks like:

include::{generated}/tu-find-by-barcode-404/http-response.adoc[]

Also the short form of a `Barcode` can be passed to the API and the server implementation adjusts the given `Barcode` to the configured
style, like it is left or right aligned and padded.

include::{generated}/tu-find-by-barcode-short/http-response.adoc[]

=== Find by multiple Barcodes
Also multiple `Barcodes` can be passed to the API in order to search for multiple `TransportUnits`:

include::{generated}/tu-find-by-barcodes/http-request.adoc[]

This returns an array with the `TransportUnits` found:

include::{generated}/tu-find-by-barcodes/http-response.adoc[]

=== Find TransportUnits on a Location
Search and return all `TransportUnits` that are currently booked on a given `Location`.

include::{generated}/tu-find-on-location/http-request.adoc[]

The `TransportUnit` with `Barcode` == `00000000000000004712` is returned:

include::{generated}/tu-find-on-location/http-response.adoc[]

