= OpenWMS.org COMMON: RESTful API (Common Service)
({bversion}-{bnumber})
Heiko Scherrer; Markus Schneider;
:doctype: book
:icons: font
:toc:
:sectanchors:
:sectlinks:
:toclevels: 4
:source-highlighter: highlightjs
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

Copyright © 2005-2025

Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies
and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.

[[overview]]
= Overview
This guide describes the RESTful API of the OpenWMS.org COMMON Base Service module and its usage. Some general terms and definitions
are explained and declared in the first part of the document whereas in the second part the usage of the API is shown in
a more use-case-driven approach.

include::0-preambel.adoc[]

include::1-sitemap.adoc[]

[[resources-prg]]
= Resources

A description of all used API resources.

image::images/ClassDiagram.svg[]

include::2-index.adoc[]

include::3-account.adoc[]

include::4-location.adoc[]

include::5-location-type.adoc[]

include::6-location-group.adoc[]

include::7-target.adoc[]

include::8-transport-unit.adoc[]

include::9-transport-unit-type.adoc[]
