= RESTful API
({bversion}-{bnumber})
Heiko Scherrer; Markus Schneider;
:doctype: book
:icons: font
:toc:
:sectanchors:
:sectlinks:
:toclevels: 4
:source-highlighter: highlightjs
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= Overview
This guide describes the RESTful API of the OpenWMS.org COMMON Base Service module and its usage. Some general terms and definitions
are explained and declared in the first part of the document whereas in the second part the usage of the API is shown in
a more use-case-driven approach.

[[sitemap-prg]]
= Interaction Map

This chapter describes the actions, respectively the flow of actions, an API consumer can perform to achieve the use cases. The COMMON
Service API deals essentially with `Locations`, `LocationGroups` and `TransportUnits` therefore those entities are centric elements in the
interaction model and can be referenced from the main index page.

Like human readable websites provide a sitemap, a machine readable API can be visualized with an interaction map. A fully automated RESTful
maturity-level-3 API offers index resources beside typical business resources. The API entry point is the top-level index resource that is
used to navigate to all possible entities with their operations.

image::common-service-index.svg[]

This top-level, or root, index page offers further links to primary resources, like `Locations`, `LocationGroups` and `TransportUnits`.

[[resources-prg]]
= Resources

A description of all used API resources.

image::ClassDiagram.svg[]

== Index

The initial HTTP request to retrieve information about all available resources looks like the following. The Index page is a public
available resource and does not need any authentication.

include::{generated}/get-index/http-request.adoc[]

The Index resource is returned in the response body with the response status of 200-OK. This main Index lists all primary resource entities
to follow next.

include::{generated}/get-index/http-response.adoc[]

A client application must only know about the agreed link names and follow the corresponding `href` link to navigate further.

== Location

A `Location` represents a physical or virtual place in a warehouse. Could be something like a storage location in the stock or a location on
the conveyor. Even error locations can be represented with the `Location`. Multiple `Locations` with same characteristics are grouped to a
`LocationGroup`.

A `Location` is identified by the 5-tuple coordinate, the LocationID, as well as a persistent key (the pKey). The PLC Code is an additional
identifier of a `Location` that might be null in project setups. It is the identifying name a PLC unit uses in automatic warehouses - not
used in manual warehouses.

A `Location` always belongs to a `LocationGroup` where the name of that group is stored in the `locationGroupName` property.

A `Location` can be a `Target` to send `TransportUnits` to, i.e. the target of an automatic `TransportOrder` or a manual `Movement`.

Multiple state properties with different meaning exist for a `Location`. The `plcState` is exclusively managed by the PLC in automatic
warehouses. Any error signaled by the PLC are stored on this field with a value greater than 0. Two other state fields `incomingActive` and
`outgoindActive` are used to control the material flow control of this `Location`. If `incomingActive` is set to `false`, the particular
`Location` is not considered in Inbound activities, like Putaway. Whereas the `outgoindActive` can be set to `false` to lock Outbound
operations off this `Location`.

The API allows to search for `Locations` and to mutate the `Locations` state.

=== Location Index
The Location Index with all possible operations can be retrieved with the following GET request:

include::{generated}/loc-index/http-request.adoc[]

The response lists all the operations with a name and the corresponding href link:

include::{generated}/loc-index/http-response.adoc[]

=== Find Location by Coordinate
Send a HTTP GET request with the 5-tuple coordinate as query parameter to find a `Location` identified by this coordinate.

include::{generated}/loc-find-coordinate/http-request.adoc[]

If the `Location` exists the server responds with

include::{generated}/loc-find-coordinate/http-response.adoc[]

If the `Location` with the requested coordinate does not exist, the server responds with

include::{generated}/loc-find-coordinate-404/http-response.adoc[]

If the passed coordinate is not well formatted and rejected by the server the response looks like

include::{generated}/loc-find-coordinate-400/http-response.adoc[]

=== Find Location by Coordinate with Wildcards
The API to search for `Locations` also accepts typical SQL wildcards in each part of the 5-tuple coordinate. Let's assume one searches for
all Lift `Locations` in the Flat Good area, this could look like this:

include::{generated}/loc-find-coordinate-wildcard/http-request.adoc[]

In this case the Flat Good area has only 2 Lift positions and the server returns both:

include::{generated}/loc-find-coordinate-wildcard/http-response.adoc[]

If the search query did not find any `Locations` the server responds with:

include::{generated}/loc-find-coordinate-wildcard-404/http-response.adoc[]

=== Find Location by PLC code
Send a HTTP GET request with the PLC code as query parameter to find a `Location` identified by this PLC code.

include::{generated}/loc-find-plc/http-request.adoc[]

If the `Location` exists the server responds with

include::{generated}/loc-find-plc/http-response.adoc[]

If no `Location` with the requested PLC code exists, the server responds with

include::{generated}/loc-find-plc-404/http-response.adoc[]

=== Find Locations of a LocationGroup
Send a HTTP GET request with the name of a `LocationGroup` as query parameter to find all `Locations` that belong to this group.

include::{generated}/loc-find-in-lg/http-request.adoc[]

The server responds with the list of all `Locations` - the name of the `LocationGroup` is not validated.

include::{generated}/loc-find-in-lg/http-response.adoc[]

The server accepts multiple `LocationGroup` names as request parameter to get a combined list of `Locations` that belong to group with name
`ZILE` and `FGRECEIVING`:

include::{generated}/loc-find-in-lg-multiple/http-request.adoc[]

Wildcards in the `LocationGroup` name are supported if only one `LocationGroup` name is provided:

include::{generated}/loc-find-in-lg-wc/http-request.adoc[]

The response is a list of `Locations` that belong to a `LocationGroup` where the name starts with `IP` (matching the groups `IPOINT`,
`IPOINT1` and `IPOINT2` in this example:

include::{generated}/loc-find-in-lg-wc/http-response.adoc[]

=== Change a Location's State
Send a HTTP PATCH request with the persistent identifying key of an existing `Location` along the new state decoded as `ErrorCodeVO` request
parameter.

include::{generated}/loc-state-404/http-request.adoc[]

If the `Location` with the given persistent key does not exist, the server responds with

include::{generated}/loc-state-404/http-response.adoc[]

The `ErrorCodeVO` contains a ternary error bitmap that decodes all state information. It is expected as 8-digit String with allowed symbols
`*|0|1`. Each digit is assigned to one of the state attribute of the `Location` or `LocationGroup`:

|===
| Digit Position (RtL) | Assigned attribute
| 2^0^                 | Location.incomingActive
| 2^1^                 | Location.outgoingActive
| 2^2^                 | Location.groupStateIn
| 2^3^                 | Location.groupStateOut
|===

The following table shows all currently accepted decodings of the `ErrorCodeVO.errorCode` String that is sent with the request body:
|===
| ErrorCode String                                                                   | Description
| `{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}` | Content is ignored
| `{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}00`                   | Release Location for Inbound and Outbound operations
| `{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}01`                   | Lock Inbound operation to the Location
| `{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}10`                   | Lock Outbound operation from the Location
| `{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}11`                   | Lock Inbound and Outbound operation for the Location
|===

In this example a `Location` identified with the given persistent key is locked for Inbound operations with the following request:

include::{generated}/loc-state-in/http-request.adoc[]

If the server could lock the `Location` successfully the response looks like:

include::{generated}/loc-state-in/http-response.adoc[]

Beside locking the `Location` for Inbound- and Outbound processing it is also possible to change the PLC state of the `Location` through
this API. Therefor the `ErrorCodeVO` data structure contains a property `plcState` that can be set to a numeric integer value. Usually a
PLC state of `0` means the `Location` is not blocked and available for any operation. A PLC may set the state to a value greater than 0 to
signal an error occurred on the `Location`.

Set the `plcState` to `31` (In terms of https://interface21-io.gitbook.io/osip[OSIP] this means `Location unexpected occupied`):

include::{generated}/loc-plcstate/http-request.adoc[]

If the server could set the state successfully the response is:

include::{generated}/loc-plcstate/http-response.adoc[]

== LocationGroup

A `LocationGroup` is used to group `Locations` with same characteristics or to define a warehouse area that can be seen as one cohesive
block controlled by one single subsystem.

=== LocationGroup Index
The index with all possible operations can be retrieved with the following GET request:

include::{generated}/lg-index/http-request.adoc[]

The response lists all the operations with a name and the corresponding href link:

include::{generated}/lg-index/http-response.adoc[]

=== Find all LocationGroups
To retrieve a list of all existing `LocationGroups` a client must send a GET request to the server:

include::{generated}/lg-find-all/http-request.adoc[]

If no `LocationGroups` exist the returned array is empty otherwise the response looks like:

include::{generated}/lg-find-all/http-response.adoc[]

Each `LocationGroup` has a link to its parent `LocationGroup` except the root `LocationGroup` that has no parent. Notice the returned
`Content-Type` is `application/hal+json` that enables support for hypermedia links.

=== Find LocationGroup by Name
Send a HTTP GET request with the unique name of the `LocationGroup`.

include::{generated}/lg-find-name/http-request.adoc[]

If the `LocationGroup` exists the server responds with

include::{generated}/lg-find-name/http-response.adoc[]

If the `LocationGroup` with the given name does not exist, the server responds with

include::{generated}/lg-find-name-404/http-response.adoc[]

=== Find multiple LocationGroups by Name
Send a HTTP GET request with a list of unique `LocationGroup` names.

include::{generated}/lg-find-names/http-request.adoc[]

The server sends back a list of all `LocationGroups` or an empty list if no `LocationGroups` exist.

include::{generated}/lg-find-names/http-response.adoc[]

== Target
A `Target` is a `Location` or a group of `Locations` (`LocationGroup`) where a `TransportUnit` may be sent to.

A `Target` can be locked for *inbound*/*outbound*, for *operation* or for both. When the `Target` is locked for inbound, no new
`TransportUnit` movements (`TransportOrders` in automatic warehouses) are created to this `Target` (like a Putaway lock).
In contrast, no movements can be created away from this `Target` if it is locked for outbound (like Allocation). Locking inbound/outbound
has no impact on the operation mode of the `Target`. So the `Target` may _still process_ existing orders, even if it is locked for
inbound/outbound.

The operation mode of a `Target` is controlled separately. If the `Targets` operation mode is set to `*BLOCKED*` the `Target` stops
all operations and does no longer process any commands or telegrams.

=== Locking Inbound/Outbound
Locking the Inbound/Outbound of a `Target` is controlled with a HTTP POST request against the URI `/v1/targets/{name}` with a set of
query parameters.

|===
| HTTP Verb | Query Param `type` | Query Param `mode` | Description
| `POST`
| `ALLOCATION_LOCK`
| `IN`
| Lock the `Target` for Inbound allocation


| `POST`
| `ALLOCATION_LOCK`
| `OUT`
| Lock the `Target` for Outbound allocation


| `POST`
| `ALLOCATION_LOCK`
| `IN_AND_OUT`
| Lock the `Target` for Inbound and Outbound allocation


| `POST`
| `ALLOCATION_LOCK`
| `NONE`
| Release the `Target` for all kind of allocation
|===

==== Lock Inbound (Putaway, Infeed)
To lock a `Target` to be not considered in inbound, like Putaway, the server requires a HTTP POST request with the lock type
`type=ALLOCATION_LOCK` and the `*mode=IN*`.

include::{generated}/all-lock-in-lg-IPOINT/http-request.adoc[]

==== Lock Outbound (Dispatching, Allocation, Outfeed)
To lock a `Target` for outbound, like Allocation and Outfeed, the server requires a HTTP POST request with the lock type
`type=ALLOCATION_LOCK` and the `*mode=OUT*`.

include::{generated}/all-lock-out-lg-IPOINT/http-request.adoc[]

==== Lock Inbound & Outbound
To lock a `Target` for inbound and outbound, like Putaway and Allocation, the server requires a HTTP POST request with the
lock type `type=ALLOCATION_LOCK` and the `*mode=IN_AND_OUT*`.

include::{generated}/all-lock-inout-lg-IPOINT/http-request.adoc[]

==== Release Lock
To release all locks on a `Target` and allow any inbound and outbound operation, the server requires a HTTP POST request with the lock
type `type=ALLOCATION_LOCK` and the `*mode=NONE*`.

include::{generated}/all-lock-none-lg-IPOINT/http-request.adoc[]

==== Response: Success
In any of the previous cases the server responds with the following success message.

include::{generated}/all-lock-none-lg-IPOINT/http-response.adoc[]

=== Locking Operational Processing
A `Target` could also be locked for operation only but not for further Allocation. This means, the `Target` is active and looks available
in warehouse counting and order allocation but is currently out-of-order and not ready to execute any (physical) operation. This is useful
for planned short term locks, where a `Target` is taken out of operation but should still be considered by the system.

Like the infeed/outfeed locking an *operational lock* can be set to different modes.

|===
| HTTP Verb | Query Param `type` | Query Param `mode` | Description
| `POST`
| `OPERATION_LOCK`
| `IN`
| Lock the `Target` for all inbound operations


| `POST`
| `OPERATION_LOCK`
| `OUT`
| Lock the `Target` for all outbound operations


| `POST`
| `OPERATION_LOCK`
| `IN_AND_OUT`
| Lock the `Target` for all inbound and outbound operations


| `POST`
| `OPERATION_LOCK`
| `NONE`
| Release the `Target` for all kind of operations
|===

==== Lock for inbound Operations
To lock a `Target` for inbound operations only, the server requires a HTTP POST request with the lock type
`type=OPERATION_LOCK` and the `*mode=IN*`.

include::{generated}/all-olock-in-lg-IPOINT/http-request.adoc[]

==== Lock for outbound Operations
To lock a `Target` for outbound operations only, the server requires a HTTP POST request with the lock type
`type=OPERATION_LOCK` and the `*mode=OUT*`.

include::{generated}/all-olock-out-lg-IPOINT/http-request.adoc[]

==== Lock inbound & outbound Operations
To lock a `Target` for inbound and outbound operations, the server requires a HTTP POST request with the
lock type `type=OPERATION_LOCK` and the `*mode=IN_AND_OUT*`.

include::{generated}/all-olock-inout-lg-IPOINT/http-request.adoc[]

==== Release Lock
To release all operational locks on a `Target` and allow any inbound and outbound operation, the server requires a HTTP POST request with
the lock type `type=OPERATION_LOCK` and the `*mode=NONE*`.

include::{generated}/all-olock-none-lg-IPOINT/http-request.adoc[]

==== Response: Success
In any of the previous cases the server responds with the following success message.

include::{generated}/all-olock-none-lg-IPOINT/http-response.adoc[]

=== Locking / Unlocking a Target for Allocation and Processing
If a `Target` locked for operation it does not process and requests anymore. In case of a physical `Target`, like a Crane, no new movements
are accepted and the Crane will stop working. This depends on the implemented Crane strategy. The Crane could stop immediately or after it
finishes the current operation.

To permanently lock or unlock a `Target` for allocation _and_ processing send a HTTP POST request with the name of the `Target` to the
server. Locking  the `Target` allows an optional flag to signal a re-allocation of already assigned movements and orders.

In this example the `Target` is a `LocationGroup` with the name `IPOINT` that gets locked. The server is requested to re-allocate existing
orders.

include::{generated}/lock-lg-IPOINT/http-request.adoc[]

To unlock the same `Target` with name `IPOINT`:

include::{generated}/unlock-lg-IPOINT/http-request.adoc[]

==== Response: Success
If the server has successfully locked or unlocked the `Target` the response is:

include::{generated}/lock-lg-IPOINT/http-response.adoc[]

==== Response: Target does not exist
If the given `Target` (FOO) does not exist the server responds with:

include::{generated}/lock-lg-unknown/http-response.adoc[]





