#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin
docker push openwms/org.openwms.common.service:latest
docker push openwms/org.openwms.common.service:$VERSION-$GITHUB_RUN_NUMBER
