[[section-introduction-and-goals]]
== Introduction and Goals

=== Requirements Overview

The required and demanded functionality of the Common Service is comprised by the issues tracked in GitHubs issue tracker. All open issues
that are assigned to an upcoming milestone are accepted for implementation and will likely be implemented and released.

Open pending issues
[options="header"]
|===
| Issue ID | Planned Milestone | Title
include::openGitHubIssues.adoc[]
|===

All functionality that is currently included has already been implemented and the corresponding issues are closed. A list of all closed
issues with their resolved milestone release is shown below. Notice that issues may be closed but the implementation has been rejected.

Closed issues, either implemented or rejected

[role="owmsExpand"]
****
[options="header"]
|===
| Issue ID | State | Assigned Milestone | Title
include::closedGitHubIssues.adoc[]
|===
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

[cols="1,2,3,4,5" options="header"]
|===
| **Priority** | **Characteristic** | **Scenario** | **Activity** | **Risk**
|  |  |  |  |
|===
