[[section-introduction-and-goals]]
== Introduction and Goals

=== Requirements Overview

The required and demanded functionality of the Common Service is comprised by the issues tracked in GitHubs issue tracker. All open issues
that are assigned to an upcoming milestone are accepted for implementation and will likely be implemented and released.

Open pending issues
[options="header"]
|===
| Issue ID | Planned Milestone | Title
include::openGitHubIssues.adoc[]
|===

All functionality that is currently included, has already been implemented and the corresponding issues are closed. A list of all closed
issues with their resolved milestone release is shown below. Notice that issues may be closed but the implementation has been rejected.

Closed issues, either implemented or rejected

[role="owmsExpand"]
****
[options="header"]
|===
| Issue ID | State | Assigned Milestone | Title
include::closedGitHubIssues.adoc[]
|===
****

=== Quality Goals

[cols="1,2,3,4,5" options="header"]
|===
| **Priority** | **Characteristic** | **Scenario** | **Activity** | **Risk**
|  |  |  |  |
|===
