[[section-concepts]]
== Cross-cutting Concepts

=== Configuration
The default service configuration is provided internally with a multi-profile `application.yml` YAML file. The default values are meant to
be overridden on any development or production environment, either by system variables or by a centrally managed configuration server.

In a distributed microservice environment a configuration server (OpenWMS.org Configuration Server) is used to provide environment specific
configuration to all services and manage this in a single place.

If the configuration of the service is being updated on the configuration server, the service needs to be restarted in order to fetch the
configuration at startup. A second and better approach is to update the configuration of the service at runtime without any service
downtime. This can either happen via Spring Actuator endpoints (in a `SYNCHRONOUS` environment) or via RabbitMQ events in an `ASYNCHRONOUS`
environment with a RabbitMQ message broker.
